blank_issues_enabled: false
contact_links:
  - name: "Feature Request [DISABLED]"
    about: "We are temporarily not taking any new feature requests."
    url: "https://discord.gg/GzdQdMw"
  - name: "Get Support"
    url: "https://discord.gg/GzdQdMw"
    about: "Need help using AE? Join our Discord Server for help!"
